config/routes.rb
Eveyl::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  resources :home, only: [:index]

  resource :user, only: [:show] do
    resources :api_keys, only: [:show, :new, :create, :destroy]

    resource :user_profile, only: [:show, :update]
  end

  resources :orders, only: [:show, :index] do
    collection do
      get :recent
      post :search
    end
  end

  resources :accounts, only: [:show, :index] do
    resources :characters, only: [:show, :index]
  end

  resources :character_assets, only: [:index] do
    collection do
      post :search
    end
  end

  resources :characters, only: [:show, :index] do
    resources :character_assets, only: [:index] do
      collection do
        post :search
      end
    end
  end

  resources :corporations, only: [:index, :show]

  resources :types, only: [:index, :show]

  resources :regions, only: [:index, :show] do
    resources :solar_systems, only: [:index, :show] do
      resources :stations, only: [:index]
    end
  end

  resources :market_groups, only: [:index, :show]

  resources :blueprints

  resources :api_logs, only: [:index]

  resource :status, only: [:show]

  resource :links, only: [:show]

  namespace :api, defaults: {format: 'json'}, only: [:index, :show, :create, :update, :destroy] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      root :to => 'root#index'

      resources :regions, only: [:index, :show] do
        resources :solar_systems, only: [:index, :show]

        collection do
          get :names
        end
      end

      resources :solar_systems, only: [:index, :show] do
        collection do
          get :names
        end
      end

      resources :types, only: [:index, :show] do
        resource :order_histories, only: [:show]
        resources :orders, only: [:index]
        collection do
          get :names
        end
      end

      resources :orders, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :order_histories, only: [:search] do
        collection do
          get :search
        end
      end

      resources :order_stats, only: [:search] do
        collection do
          get :search
        end
      end

      match "*path", :to => "api#not_found"
    end
  end

  root :to => "home#index"
end

app/models/solar_system.rb
class SolarSystem < ActiveRecord::Base
  belongs_to :region

  has_many :stations
  has_many :orders

  has_one :sovereignty

  has_one :faction, :through => :sovereignty
  has_one :alliance, :through => :sovereignty
  has_one :corporation, :through => :sovereignty

  belongs_to :constellation

  has_many :solar_system_stats

  delegate :name, :to => :region, :prefix => true
  delegate :name, :to => :constellation, :prefix => true
  delegate :name, :to => :faction, :prefix => true, :allow_nil => true
  delegate :name, :to => :alliance, :prefix => true, :allow_nil => true

  validates_presence_of :name

  validates :region_id, :presence => true, :numericality => true
  validates :constellation_id, :presence => true, :numericality => true
  validates :security, :presence => true, :numericality => true

  def self.ids
    self.pluck(:solar_system_id)
  end

  def self.by_name(q)
    where("name ilike ?", "%#{q}%")
  end

  def self.names(q = nil)
    if q.nil?
      select([:name, :solar_system_id]).order("name asc")
    else
      select([:name, :solar_system_id]).where("name ilike ?", "%#{q}%").order("name asc")
    end
  end

  def stats_48h
    solar_system_stats.last_48h
  end

  def stats_72h
    solar_system_stats.last_72h
  end

  def dotlan_url
    "http://evemaps.dotlan.net/system/" + name.gsub(' ', '_')
  end
end

app/controllers/api/v1/solar_systems_controller.rb
class Api::V1::SolarSystemsController < Api::ApiController
  before_filter :parse_params

  def index
    systems = SolarSystem
    systems = systems.where(region_id: params[:region_id]) if params[:region_id]
    systems = systems.by_name(params[:q]) if params[:q]

    systems = systems.order("solar_system_id asc")

    @pc = PagedCollection.new(systems, @page, @rpp,
                              api_solar_systems_path)

    render :index
  end

  def show
    @solar_system = SolarSystem.includes(:solar_system_stats, :stations).find(@system_id)

    render :show
  end

  def names
    @names = SolarSystem.names(params[:q])

    render :names
  end

  protected

  def parse_params
    if params[:id]
      return head :bad_request if params[:id] !~ /^\d{8}$/

      @system_id = params[:id].to_i
    end
  end
end

app/controllers/solar_systems_controller.rb
class SolarSystemsController < ApplicationController
  respond_to :html

  before_filter :find_region, only: [:index]

  def index
    systems = SolarSystem.where(region_id: params[:region_id])
                         .order("name asc")
    @solar_systems = SolarSystemDecorator.decorate_collection(systems) #.first

    respond_with @solar_systems
  end

  def show
    @solar_system = SolarSystem.find(params[:id]).decorate

    respond_with @solar_system
  end

  protected

  def find_region
    begin
      @region = Region.find(params[:region_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to :root, notice: "Unknown Region" unless @region
      false
    end
  end
end

app/views/solar_systems/_grouped.html.haml
- cache(expires_in: 30.minutes) do
  %h2= @region.name
  %p= link_to 'Dotlan - Evemaps', @region.dotlan_url, target: "_blank"

  - @solar_systems.group_by(&:constellation_name).sort.each do |val|
    %table.table.table-hover.no-border
      %thead
        %tr
          %th(style="width: 10%")= val.first
          %th(style="width: 20%") Name
          %th(style="width: 10%") Security
          %th(style="width: 10%") Class
          %th(style="width: 20%") Faction/Alliance
          %th(style="width: 10%") Stations
      %tbody
        - val.last.each do |system|
          %tr
            %td
            %td= link_to system.name, region_solar_system_path(@region.id, system.id)
            %td= number_with_precision(system.security, precision: 2)
            %td= system.security_class
            %td= system.owner
            - if system.stations.count > 0
              %td= link_to system.stations.count, region_solar_system_stations_path(@region.id, system.id)
            - else
              %td 0

app/views/solar_systems/index.html.haml
= render "grouped"

app/views/solar_systems/show.html.haml
%h3
  #{@solar_system.name}
  %small (#{number_with_precision(@solar_system.security, precision: 2)}0)

%p
  #{@solar_system.constellation_name} /
  #{link_to @solar_system.region_name, region_path(@solar_system.region_id)}

%ul.nav.nav-tabs
  %li.active
    %a{:href => '#stats', "data-toggle" => "tab"}
      Stats
  %li
    %a{:href => '#stations', "data-toggle" => "tab"}
      Stations

%div.tab-content
  %div#stats.tab-pane.active
    %table#solar-system-stats.table.table-condensed.table-hover.no-border
      %thead
        %tr
          %th(style="width: 15%") Time
          %th(style="width: 10%") Ship Kills
          %th(style="width: 10%") Pod Kills
          %th(style="width: 10%") Faction Kills
          %th(style="width: 10%") Ship Jumps
      %tbody
        - @solar_system.solar_system_stats.each do |stat|
          %tr
            %td= stat.ts
            %td= stat.ship_kills
            %td= stat.pod_kills
            %td= stat.faction_kills
            %td= stat.ship_jumps

  %div#stations.tab-pane
    = render partial: "stations/stations_table", locals: {stations: @solar_system.stations }