config/routes.rb
Eveyl::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  resources :home, only: [:index]

  resource :user, only: [:show] do
    resources :api_keys, only: [:show, :new, :create, :destroy]

    resource :user_profile, only: [:show, :update]
  end

  resources :orders, only: [:show, :index] do
    collection do
      get :recent
      post :search
    end
  end

  resources :accounts, only: [:show, :index] do
    resources :characters, only: [:show, :index]
  end

  resources :character_assets, only: [:index] do
    collection do
      post :search
    end
  end

  resources :characters, only: [:show, :index] do
    resources :character_assets, only: [:index] do
      collection do
        post :search
      end
    end
  end

  resources :corporations, only: [:index, :show]

  resources :types, only: [:index, :show]

  resources :regions, only: [:index, :show] do
    resources :solar_systems, only: [:index, :show] do
      resources :stations, only: [:index]
    end
  end

  resources :market_groups, only: [:index, :show]

  resources :blueprints

  resources :api_logs, only: [:index]

  resource :status, only: [:show]

  resource :links, only: [:show]

  namespace :api, defaults: {format: 'json'}, only: [:index, :show, :create, :update, :destroy] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      root :to => 'root#index'

      resources :regions, only: [:index, :show] do
        resources :solar_systems, only: [:index, :show]

        collection do
          get :names
        end
      end

      resources :solar_systems, only: [:index, :show] do
        collection do
          get :names
        end
      end

      resources :types, only: [:index, :show] do
        resource :order_histories, only: [:show]
        resources :orders, only: [:index]
        collection do
          get :names
        end
      end

      resources :orders, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :order_histories, only: [:search] do
        collection do
          get :search
        end
      end

      resources :order_stats, only: [:search] do
        collection do
          get :search
        end
      end

      match "*path", :to => "api#not_found"
    end
  end

  root :to => "home#index"
end

app/controllers/api/v1/types_controller.rb
class Api::V1::TypesController < Api::ApiController
  before_filter :parse_params

  def index
    query = @on_market ? Type.on_market : Type.published

    query = query.find_by_name(params[:q]) if params[:q]

    @pc = PagedCollection.new(query, @page, @rpp,
                              api_types_path)

    render :index
  end

  def show
    @type = Type.find(@type_id) if @type_id

    return head :not_found unless @type

    render "show"
  end

  def names
    return head :bad_request unless params[:q]

    @names = Type.names(@on_market, params[:q])

    render "names"
  end

  protected

  def parse_params
    if params[:q]
      return head :bad_request if params[:q] !~ /^[\w\s\-]{2,80}$/
    end

    if params[:id]
      return head :bad_request if params[:id] !~ /^\d{2,8}$/

      @type_id = params[:id].to_i
    end

    if params[:on_market]
      return head :bad_request if params[:on_market] !~ /^0|1$/

      @on_market = params[:on_market] == '0' ? false : true
    else
      @on_market = true
    end
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  respond_to :html

  def index
  end

  def show
    @type = Type.includes(:group, :category, :market_group)
                .find(params[:id], :include => {:types => :materials})
                .decorate

    respond_with @type
  end
end

app/views/types/_assets.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th Character
      %th Region
      %th Location
      %th Container
      %th Quantity
  %tbody
    - assets.each do |a|
      %tr
        %td= a.character.name
        %td= a.region_name
        %td= a.station_name || a.system_name
        %td= a.container.try(:name) || '-'
        %td #{number_with_delimiter(a.qty, :delimiter => ',')}

%strong.pull-right
  Total: #{number_with_delimiter(@total, :delimiter => ',')}

app/views/types/_bill_of_materials.html.haml
%table.table
  %thead
    %tr
      - type.me_levels.each do |me|
        %th ME #{me}
  %tbody
    %tr
      - type.me_levels.each do |me|
        %td
          %table.table
            %thead
              %tr
                %th
                %th
                %th
                %th
              %tr
                %th Material
                %th Base
                %th Needed
                %th Wasted
            %tbody
              - type.bill_of_materials(me).materials.each do |m|
                %tr
                  %td= link_to m.name, type_path(m.type_id), target: '_blank'
                  %td= m.base
                  %td= m.needed
                  %td= m.wasted

app/views/types/_blueprint.html.haml
%ul.nav.nav-tabs
  %li.active
    %a{:href => '#detail', 'data-toggle' => 'tab'}
      Detail
  %li
    %a{:href => '#materials', 'data-toggle' => 'tab'}
      Materials
  %li
    %a{:href => '#build', 'data-toggle' => 'tab'}
      Build Time

%div.tab-content
  %div#detail.tab-pane.active
    .row
      .span10
        %div#detail.tab-pane
          %table.table.table-striped
            %thead
              %tr
                %th(style="width: 50%")
                %th(style="width: 50%")
            %tbody
              %tr
                %td Group
                %td #{type.group_name}
              %tr
                %td Market Group
                %td #{type.market_group_chain}
              %tr
                %td Product
                %td= link_to type.product_name, type_path(type.product_id)
              %tr
                %td Base Production Time
                %td= type.production_time
              %tr
                %td Base Research Productivity Time
                %td= type.research_productivity_time
              %tr
                %td Base Research Material Time
                %td= type.research_material_time
              %tr
                %td Base Research Copy Time
                %td= type.research_copy_time
              %tr
                %td Base Invention Time
                %td= type.research_tech_time
              %tr
                %td Max runs
                %td #{type.max_production_limit}
              %tr
                %td Waste Factor
                %td #{type.waste_factor}%

    %table.table
      %thead
        %tr
          %th Skill
          %th Level
      %tbody
        - type.bill_of_materials.skills.each do |m|
          %tr
            %td= link_to m.name, type_path(m.type_id), target: '_blank'
            %td= m.base

  %div#materials.tab-pane
    .span6
      = render :partial => "types/bill_of_materials", locals: {type: type}

  %div#build.tab-pane
    %p=#Build_Time = Production_Time * (1 - ((Productivity_Modifier / Production_Time) * (PL / (1 + PL)))) * (1 - (0.04 * Industry_Skill))

app/views/types/_detail.html.haml
- if type.is_blueprint?
  = render :partial => "types/blueprint", locals: {type: type}
- else
  %div#detail.tab-pane
    %table.table.table-striped
      %thead
        %tr
          %th(style="width: 15%")
          %th(style="width: 85%")
      %tbody
        %tr
          %td Description
          %td #{type.description.to_s.gsub("\n", '<br>').html_safe}
        %tr
          %td Volume
          %td #{type.volume}
        %tr
          %td Category
          %td #{type.category_name}
        %tr
          %td Group
          %td #{type.group_name}
        %tr
          %td Market Group
          %td
            - if type.market_group
              #{type.market_group.group_chain.map(&:name).join(' / ')}
        - if type.tech_level
          %tr
            %td Tech / Meta Level
            %td
              T#{type.tech_level}
              -if type.meta_level
                M#{type.meta_level}
        - if type.has_blueprint?
          %tr
            %td Blueprint
            %td= link_to type.blueprint_name, type_path(type.blueprint_type_id)
        - if type.has_materials?
          %tr
            %td
              Materials
              - if type.portion_size.to_i > 1
                %p (for #{type.portion_size})
            %td
              = render "types/mat_table", type: type
        - if type.has_materials? && type.mat_value(current_user)
          %tr
            %td Material Value
            %td
              %strong
                %a{:href => '#', :rel => 'tooltip', :title => "#{type.value_ts(current_user)}"}
                  #{type.mat_value(current_user)}
        %tr
          %td Estimated Value
          %td
            - if type.mkt_value(current_user)
              %strong
                %a{:href => '#', :rel => 'tooltip', :title => "#{type.value_ts}"}
                  #{type.mkt_value(current_user)}
            - else
              %em.text-warning Unknown

        - if type.has_materials?
          %tr
            %td Material %
            %td #{type.mat_perc(current_user)}%

app/views/types/_mat_table.html.haml
%table.mat-table
  %tbody
    - type.materials.each do |m|
      %tr
        %td.name #{link_to m.type_name, type_path(m.material_type_id), target: "_blank"}
        %td.qty #{number_with_delimiter(m.quantity)}
        %td #{m.type.mkt_value(current_user) ? number_with_delimiter(m.type.mkt_value(current_user)) : '-'}
        %td
          - if m.type.mkt_value(current_user)
            #{format_price(m.type.mkt_value(current_user) * m.quantity)}

app/views/types/index.html.haml
%h1 Items

%form{:action => '/orders/search', :method => 'post', :autocomplete => "off"}
  %input{:type => 'text', :id => 'item-input', :name => 'item_name', :autocomplete => "off"}
  %input{:type => 'text', :id => 'region-input', :name => 'region_name', :autocomplete => "off"}
  %input{:type => 'hidden', :id => 'type-id', :name => 'type_id'}
  %input{:type => 'hidden', :id => 'region-id', :name => 'region_id'}

  %input{:type => 'submit', :value => 'Search', :class => 'btn'}

app/views/types/show.html.haml
%div.header
  .pull-left
    %img.type-icon{src: "http://evefiles.capsuleer.de/types/#{@type._id}_64.png"}
  %h3= @type.name
  %h5= link_to 'Orders', search_orders_path(type_id: @type.id, hisec_only: 'on'), :method => :post

= render :partial => "types/detail", :locals => { :type => @type }

- if @assets
  = render :partial => "types/assets", :locals => { :assets => @assets }