config/routes.rb
Eveyl::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  resources :home, only: [:index]

  resource :user, only: [:show] do
    resources :api_keys, only: [:show, :new, :create, :destroy]

    resource :user_profile, only: [:show, :update]
  end

  resources :orders, only: [:show, :index] do
    collection do
      get :recent
      post :search
    end
  end

  resources :accounts, only: [:show, :index] do
    resources :characters, only: [:show, :index]
  end

  resources :character_assets, only: [:index] do
    collection do
      post :search
    end
  end

  resources :characters, only: [:show, :index] do
    resources :character_assets, only: [:index] do
      collection do
        post :search
      end
    end
  end

  resources :corporations, only: [:index, :show]

  resources :types, only: [:index, :show]

  resources :regions, only: [:index, :show] do
    resources :solar_systems, only: [:index, :show] do
      resources :stations, only: [:index]
    end
  end

  resources :market_groups, only: [:index, :show]

  resources :blueprints

  resources :api_logs, only: [:index]

  resource :status, only: [:show]

  resource :links, only: [:show]

  namespace :api, defaults: {format: 'json'}, only: [:index, :show, :create, :update, :destroy] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      root :to => 'root#index'

      resources :regions, only: [:index, :show] do
        resources :solar_systems, only: [:index, :show]

        collection do
          get :names
        end
      end

      resources :solar_systems, only: [:index, :show] do
        collection do
          get :names
        end
      end

      resources :types, only: [:index, :show] do
        resource :order_histories, only: [:show]
        resources :orders, only: [:index]
        collection do
          get :names
        end
      end

      resources :orders, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :order_histories, only: [:search] do
        collection do
          get :search
        end
      end

      resources :order_stats, only: [:search] do
        collection do
          get :search
        end
      end

      match "*path", :to => "api#not_found"
    end
  end

  root :to => "home#index"
end

app/models/character.rb
class Character < ActiveRecord::Base
  scope :shown, where(hidden: false)

  belongs_to :api_key, primary_key: :key_id, foreign_key: :key_id

  belongs_to :corporation
  belongs_to :alliance

  has_many :character_assets
  has_many :skills, class_name: 'CharacterSkill'

  has_one :skill_in_training, class_name: 'SkillInTraining'

  delegate :name, to: :corporation, prefix: true, allow_nil: true
  delegate :name, to: :alliance, prefix: true, allow_nil: true

  validates :name, presence: true

  def self.extract_attributes(result)
    {intelligence: result.attributes.intelligence.to_i,
     memory: result.attributes.memory.to_i,
     charisma: result.attributes.charisma.to_i,
     perception: result.attributes.perception.to_i,
     willpower: result.attributes.willpower.to_i,
    }
  end

  def self.update_from_api(key, result)
    return unless result

    c = self.find_or_create_by_character_id(result.characterID.to_i)
    the_update = {name: result.name,
                  dob: result.DoB,
                  gender: result.gender,
                  race: result.race,
                  bloodline: result.bloodLine,
                  ancestry: result.ancestry,
                  clone_name: result.cloneName,
                  clone_sp: result.cloneSkillPoints,
                  balance: result.balance,
                  corporation_id: result.corporationID.to_i,
                  cached_until: result.cached_until,
                  api_key: key,
                 }

    the_update.merge! extract_attributes(result)

    if result.respond_to?(:allianceID)
      the_update[:alliance_id] = result.allianceID
    end

    c.update_attributes(the_update, without_protection: true)
  end

  def build_assets(result)
    return unless result

    CharacterAsset.where(character_id: self.id).destroy_all

    result.assets.each do |asset|
      CharacterAsset.create_from_api(self.id, asset)
    end
  end

  def total_sp
    skills.sum(&:skill_points)
  end

  def get_skill(name)
    skills.find_by_name(name)
  end

  def get_level_for_skill(name)
    get_skill(name).try(:level)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html, :json

  def index
    @accounts = AccountDecorator.decorate_collection(current_user.accounts)

    respond_with @accounts
  end

  def show
    @character = current_user.characters.find(params[:id])
    @skills = CharacterSkill.group_by_type(@character.character_id)

    respond_with @character
  end
end

app/views/characters/_character_skills.html.haml
- skills.keys.sort.each do |name|
  %p= name
  %table.table.table-condensed
    %thead
      %tr
        %th(style="width: 40%")
        %th(style="width: 60%")
    %tbody
      - skills[name].sort { |a,b| a.skill_name <=> b.skill_name}.each do |skill|
        %tr
          %td= link_to skill.skill_name, type_path(skill.type_id), target: '_blank'
          %td= skill.level

app/views/characters/index.html.haml
%h3 Characters

- @accounts.each do |account|
  %div.well
    %p Key ID: #{link_to account.key_id, user_path}, Paid Until: #{account.paid_until}, Last Updated: #{account.updated_at}
    %table.table
      %thead
        %tr
          %th
          %th
          %th
          %th
      %tbody
        - account.shown_characters.each do |character|
          %tr
            %td
              %img{:src => "http://image.eveonline.com/Character/#{character.character_id}_64.jpg"}
              %img{:src => "http://image.eveonline.com/Corporation/#{character.corporation_id}_32.png"}
            %td
              %p= link_to character.name, account_character_path(account, character)
              %p= link_to character.corporation_name, corporation_path(character.corporation)
              %p Currently Training: #{character.skill_in_training.try(:skill_name) || 'None'}

            %td= number_with_delimiter(character.balance.to_i, :delimiter => ',')
            %td= link_to 'Assets', character_character_assets_path(character), :class => 'btn'
            %td= link_to 'Hide', '#', :class => 'btn btn-small btn-inverse'

    - if account.shown_characters.empty?
      %strong.text-error No Characters Found

app/views/characters/show.html.haml
%div{:class => 'well character-sheet'}
  %p{:class => 'pull-left'}
    %img{:src => "http://image.eveonline.com/Character/#{@character.character_id}_128.jpg", :class => 'character-img'}
    %div
      %p{:class => 'name-title'}
        #{@character.name}
      %table{:class => 'character-overview'}
        %thead
          %tr
            %th{:class => 'label-col'}
            %th{:class => 'value-col'}
        %tbody
          %tr
            %td Skill Points
            %td
          %tr
            %td Clone
            %td #{@character.clone_name} (#{number_with_delimiter(@character.clone_sp)})
          %tr
            %td Background
            %td #{@character.race} - #{@character.bloodline} - #{@character.ancestry}
          %tr
            %td Date of Birth
            %td #{@character.dob}
          %tr
            %td Corporation
            %td #{@character.corporation_name}
          %tr
            %td Alliance
            %td #{@character.alliance_name}
          %tr
            %td Balance
            %td #{number_with_delimiter(@character.balance)}

  %hr
    %ul{:class => 'nav nav-tabs'}
      %li
        %a{:href => '#attrs', "data-toggle" => 'tab'}Attributes
      %li
        %a{:href => '#skills', "data-toggle" => 'tab'}Skills
      %li
        %a{:href => '#wallet', "data-toggle" => 'tab'}Wallet
      %li
        %a{:href => '#mail', "data-toggle" => 'tab'}Mail
      %li
        %a{:href => '#notifications', "data-toggle" => 'tab'}Notifications

    %div.tab-content
      #attrs.tab-pane.active
        %table.table
          %thead
            %tr
              %th
              %th
          %tbody
            %tr
              %td Intelligence
              %td #{@character.intelligence}
            %tr
              %td Perception
              %td #{@character.perception}
            %tr
              %td Charisma
              %td #{@character.charisma}
            %tr
              %td Willpower
              %td #{@character.willpower}
            %tr
              %td Memory
              %td #{@character.memory}
      %div{:class => 'tab-pane', :id => 'skills'}
        = render 'character_skills', skills: @skills

      %div{:class => 'tab-pane', :id => 'wallet'}
        TBD

      %div{:class => 'tab-pane', :id => 'mail'}
        TBD

      %div{:class => 'tab-pane', :id => 'notifications'}
        TBD