config/routes.rb
Eveyl::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :passwords => "users/passwords"}

  resources :home, only: [:index]

  resource :user, only: [:show] do
    resources :api_keys, only: [:show, :new, :create, :destroy]

    resource :user_profile, only: [:show, :update]
  end

  resources :orders, only: [:show, :index] do
    collection do
      get :recent
      post :search
    end
  end

  resources :accounts, only: [:show, :index] do
    resources :characters, only: [:show, :index]
  end

  resources :character_assets, only: [:index] do
    collection do
      post :search
    end
  end

  resources :characters, only: [:show, :index] do
    resources :character_assets, only: [:index] do
      collection do
        post :search
      end
    end
  end

  resources :corporations, only: [:index, :show]

  resources :types, only: [:index, :show]

  resources :regions, only: [:index, :show] do
    resources :solar_systems, only: [:index, :show] do
      resources :stations, only: [:index]
    end
  end

  resources :market_groups, only: [:index, :show]

  resources :blueprints

  resources :api_logs, only: [:index]

  resource :status, only: [:show]

  resource :links, only: [:show]

  namespace :api, defaults: {format: 'json'}, only: [:index, :show, :create, :update, :destroy] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      root :to => 'root#index'

      resources :regions, only: [:index, :show] do
        resources :solar_systems, only: [:index, :show]

        collection do
          get :names
        end
      end

      resources :solar_systems, only: [:index, :show] do
        collection do
          get :names
        end
      end

      resources :types, only: [:index, :show] do
        resource :order_histories, only: [:show]
        resources :orders, only: [:index]
        collection do
          get :names
        end
      end

      resources :orders, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :order_histories, only: [:search] do
        collection do
          get :search
        end
      end

      resources :order_stats, only: [:search] do
        collection do
          get :search
        end
      end

      match "*path", :to => "api#not_found"
    end
  end

  root :to => "home#index"
end

app/models/market_group.rb
class MarketGroup < ActiveRecord::Base
  scope :top_level, where(:parent_group_id => nil)

  has_many :types

  belongs_to :parent, :class_name => 'MarketGroup', :foreign_key => :parent_group_id

  has_many :children, :class_name => 'MarketGroup', :primary_key => :market_group_id,
                                                    :foreign_key => :parent_group_id

  validates_presence_of :name
  validates :market_group_id, :presence => true, :numericality => true

  def self.minerals
    types = self.find_by_name('Minerals').try(:types)
    raise ActiveRecord::RecordNotFound unless types

    types
  end

  def stub?
    false
    # FIXME - Probably a better way
#    children.empty? || children.map(&:types).flatten.blank?
  end

  def group_chain
    chain = []

    group = self
    while group
      chain.unshift group
      group = group.parent
    end

    chain
  end
end

app/controllers/market_groups_controller.rb
class MarketGroupsController < ApplicationController
  respond_to :html, :json

  def index
    @groups = MarketGroup.top_level
  end

  def show
    @group = MarketGroup.find(params[:id])

    return 404 unless @group

    respond_with @group
  end
end

app/views/market_groups/index.html.haml
%h3 Market

#accordion2.accordion
  - @groups.each do |group|
    .accordion-group
      %div.accordion-heading
        %p.market-group-accord
          %a.accordion-toggle{"data-toggle" => "collapse", "data-parent" => "#accordion2", :href => "#collapse-#{group.id}"}
            #{group.name}
      %div.accordion-body.collapse{id: "collapse-#{group.id}"}
        .accordion-inner
          - group.children.each_slice(3) do |child|
            .row
              %p.span3= link_to child[0].name, market_group_path(child[0].id) if child[0]
              %p.span3= link_to child[1].name, market_group_path(child[1].id) if child[1]
              %p.span3= link_to child[2].name, market_group_path(child[2].id) if child[2]

app/views/market_groups/show.html.haml
%ul.breadcrumb
  %li
    %a{href: market_groups_path} Home
    %span.divider /

  - @group.group_chain.each do |g|
    - if g == @group.group_chain.last
      %li.active= g.name
    - else
      %li
        %a{href: market_group_path(g.id)}= g.name
        %span.divider /

%h5= @group.description
%hr

- unless @group.stub?
  - @group.children.each_slice(3) do |child|
    .row
      %p.span4= link_to child[0].name, market_group_path(child[0]) if child[0]
      %p.span4= link_to child[1].name, market_group_path(child[1]) if child[1]
      %p.span4= link_to child[2].name, market_group_path(child[2]) if child[2]
- @group.types.each_slice(3) do |type|
  .row
    %p.span4= link_to type[0].name, type_path(type[0]) if type[0]
    %p.span4= link_to type[1].name, type_path(type[1]) if type[1]
    %p.span4= link_to type[2].name, type_path(type[1]) if type[2]